#obj1=open("F:\poemBTH.txt","r")
#s1=obj1.readline()
#s2=obj1.readline(10)
#s3=obj1.read(15)
#print(s3)
#print(obj1.readline())
#obj1.close()
file=open("F:\contact.cvs.txt","a")
name=input("enter the name")
ph=input("enter the phon number")
file.write(name+","+ph+"\n")
#print(file.read())
file.close()
